<?php

//Version 7.1.2 -> 7.1.3 updates
function ou_profile_update_7103( &$sandbox )
{

/*
	1. : Add unit level 2, 3 & 4 fields to ou_unit content type
	2. : Add new view "ou_units"
	3. : Update "Unit ref" field on "allowed_sites" content type to point to new view
	4. : Update PIMS profile content type. Added : field_pims_l2_estab_unit_code, field_pims_l3_estab_unit_code, field_pims_l4_estab_unit_code
	
	5. : New "profile_taxonomy"
	6. : New "media_expertise" taxonomy
	
	7. : Update "profile" content type and add "profile_taxonomy"
	8. : Update "profile" content type and add "media_expertise"
	
	9. : Update "allowed_sites" add "profile_taxonomy"
	10. : Update "allowed_sites" add "media_expertise"
	
	
	
*/

}
